### PR TITLE
Feat/gui screencapture

### PR DESCRIPTION
**Pull request by JJSnader**
This adds the ability to copy an image of the current puzzle with rank, total points, and high scores included.

### CODE REVIEW

**Comment by JonathanMathBoi** [comment]
Heads up @JJSnader. It looks like there are merge conflicts in GuiView. You may want to try to resolve those before review so you don't get the fun review invalidation thing.

**Comment by JJSnader** [comment]
I tried fixing it from GitHub 's crappy mobile interface, but I think I'll need a real computer to actually merge it properly. Just leave this sit here and I'll get it merged later today.

**Review by ljvance — APPROVED** [review]
puzzle.getinstance() if statement is unnecessary, but the actual screencapture works well.

**Comment by JJSnader** [comment]
I'm going to leave that if statement in there, in case something would change and the puzzle could actually be null in the GUI.

**Pull request merged**
