### PR TITLE
Feat/alphabetical foundwords

### PR DESCRIPTION
**Pull request by JJSnader**
The found words list in the puzzle is now sorted when a new word is added to the list. This is done in the puzzle so that the views don't have to worry about the sorting.

### CODE REVIEW

**Comment by JonathanMathBoi** [comment]
Everything looks good, but the tests for CLIController involving the found words list accidentally rely on the order of the elements. I can fix these and write tests for the found command if you want, as I'm secondary.

**Comment by JJSnader** [comment]
I would appreciate if you would rewrite the test; that should just be a matter of moving a few lines of code around, right?

**Comment by JonathanMathBoi** [comment]
If you're comfortable I can still review this, but we could request a review from Luke as well.

**Review by JonathanMathBoi — APPROVED** [review]
The code looks good. All tests pass, and the program now properly displays found words as sorted.

**Comment by JonathanMathBoi** [comment]
I've approved, but I'll leave it to you as to whether or not you want another review.

**Pull request merged**
